### ISSUE TITLE
Bad bit-wise manipulation for Mcp3008 driver

### ISSUE THREAD

**Issue by jdimpson** [raspberrypi-aa/raspberrypi-aa#3]
Line 22 of the [MCSP3008 driver](https://github.com/raspberrypi-aa/raspberrypi-aa/blob/master/spi_hardware_test.py#L22) has an error.

The code at line 22 says `return [startBit, singleEnded|(channel<<4), 0]`. The correct code is `return [startBit, (singleEnded|channel)<<4, 0]`.

If the "singleEnded" variable name means the intention is to put the ADC chip into single-ended mode for the read so that all pins are usable independently, as opposed to pseudo-differential mode so that the pins are usable in pairs for differential readings, then the bit-wise logic is bad. "singleEnded" should be OR'd with the channel (pin number) before being left-shifted.

For example, if the desired pin to read is pin 5, the as-is code incorrectly sends the bit pattern `01011000`, which is likely to result in weird behaviour as the ADC is expecting pin 5 to be working in differential mode opposite pin 4, on the assumption that pins 4 and 5 are not intended to be working differentially.
 
In the same example, he correct code for line 22 (`return [startBit, (singleEnded|channel)<<4, 0]`) sends bit pattern `11010000`, per table 5-2 of the [spec sheet](http://ww1.microchip.com/downloads/en/DeviceDoc/21295C.pdf)

Also, the comment on [line 3](https://github.com/raspberrypi-aa/raspberrypi-aa/blob/master/spi_hardware_test.py#L3) says this is a "bit-banged" implementation of SPI protocol, which is not true due to the use of the python spidev module.

**Comment by Kabariya** [comment]
hi... I need your help with this code.. at line 37 and 38 can you explain that ? 

and when we are reading data... shouldn't we first make clk high then we read and then  again we need to make clk low  by this way we are getting falling edge but here we are not getting edge and even we thing we are getting rising edge cz last instruction is set clk low then read and again it come to for loop and aging it become high and immediately low ..  according to datasheet we need falling edge to read

 I hope you are getting me...

please reply back if you can :)
